# Generated by Django 5.0 on 2023-12-29 15:29

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(default=0)),
                ('title', models.CharField(default='No Title', max_length=255)),
                ('views', models.IntegerField(default=0)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('thumbnail', models.ImageField(default='', upload_to='images/')),
                ('content', ckeditor.fields.RichTextField(blank=True, default='', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='', max_length=255)),
                ('age', models.IntegerField(default=0)),
                ('occupation', models.CharField(choices=[('Student', 'Student'), ('Professor', 'Professor'), ('Worker', 'Worker')], default='Student', max_length=50)),
                ('clg_yr', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth')], default='First', max_length=25)),
                ('deg', models.CharField(choices=[('B.tech', 'B.Tech'), ('M.Tech', 'M.Tech'), ('Ph.D', 'Ph.D'), ('BS', 'BS'), ('Dual Degree', 'Dual Degree')], default='B.Tech', max_length=50)),
                ('author_real', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
